- hosts: localhost
  connection: local
  gather_facts: False
  tasks: 
    - name: Import VPC Variables
      include_vars: vars/vpc_setup

    - name: Create Olayinka VPC
      ec2_vpc_net: 
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout

    - debug: 
        var: vpcout

    - name: create a Public Subnet in Zone1
      ec2_vpc_subnet: 
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{pubSub1Cidr}}"
        map_public: yes
        resource_tags: 
          Name: Olayinka-pubsub1 
      register: pubSub1_out 

    - name: create a Public Subnet in Zone2
      ec2_vpc_subnet: 
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        cidr: "{{pubSub2Cidr}}"
        map_public: yes
        resource_tags: 
          Name: Olayinka-pubsub2 
      register: pubSub2_out 

    - name: create a Public Subnet in Zone3
      ec2_vpc_subnet: 
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone3}}"
        state: "{{state}}"
        cidr: "{{pubSub3Cidr}}"
        map_public: yes
        resource_tags: 
          Name: Olayinka-pubsub3 
      register: pubSub3_out